-- Create sub_categories table
create table if not exists public.sub_categories (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    category_id uuid references public.categories(id) on delete cascade not null
);

-- Enable RLS
alter table public.sub_categories enable row level security;

-- Policy for reading sub-categories (Public)
create policy "Sub-categories are viewable by everyone"
on public.sub_categories for select
using (true);

-- Add sub_category_id to items table
alter table public.items 
add column sub_category_id bigint references public.sub_categories(id) on delete set null;

-- Insert some default sub-categories (Optional: Example Data)
-- Assuming you have categories already, manual insert might be safer via dashboard or separate seed script
