-- 1. Platform Settings Table
create table if not exists public.platform_settings (
    id int primary key generated by default as identity,
    enable_google_auth boolean default true
);

-- Insert default row if not exists
insert into public.platform_settings (id, enable_google_auth)
values (1, true)
on conflict (id) do nothing;

-- 2. Profiles Table (Ensure it exists with correct columns)
create table if not exists public.profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    full_name text,
    avatar_url text,
    role text default 'user',
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Auto-Create Profile Trigger
-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.profiles (id, full_name, avatar_url, role)
    values (
        new.id,
        new.raw_user_meta_data->>'full_name',
        new.raw_user_meta_data->>'avatar_url',
        'user' -- Default role
    );
    return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row
    execute procedure public.handle_new_user();
