-- 1. Create sub_categories table
create table if not exists public.sub_categories (
    id bigint generated by default as identity primary key,
    name text not null,
    category_id uuid references public.categories(id) on delete cascade not null,
    created_at timestamptz default now()
);

-- Enable RLS
alter table public.sub_categories enable row level security;

-- Policies
create policy "Public read sub-categories" 
on public.sub_categories for select 
using (true);

-- Assuming is_admin_or_mod function exists from schema.sql
create policy "Admins manage sub-categories" 
on public.sub_categories for all 
using (public.is_admin_or_mod());

-- 2. Update items table
alter table public.items 
add column if not exists sub_category_id bigint references public.sub_categories(id);

-- 3. Seed Data
-- First ensure parent categories exist (idempotent)
insert into public.categories (name, slug, icon)
values 
    ('Furniture', 'furniture', 'armchair'),
    ('Electronics', 'electronics', 'smartphone'),
    ('Clothing', 'clothing', 'shirt')
on conflict (slug) do nothing;

-- Insert Sub-Categories safely using DO block to get IDs
do $$
declare
    v_furniture_id uuid;
    v_electronics_id uuid;
    v_clothing_id uuid;
begin
    -- Get IDs
    select id into v_furniture_id from public.categories where slug = 'furniture';
    select id into v_electronics_id from public.categories where slug = 'electronics';
    select id into v_clothing_id from public.categories where slug = 'clothing';

    -- Insert Furniture Subs
    if v_furniture_id is not null then
        insert into public.sub_categories (name, category_id)
        select 'Chairs', v_furniture_id
        where not exists (select 1 from public.sub_categories where name = 'Chairs' and category_id = v_furniture_id);

        insert into public.sub_categories (name, category_id)
        select 'Tables', v_furniture_id
        where not exists (select 1 from public.sub_categories where name = 'Tables' and category_id = v_furniture_id);

        insert into public.sub_categories (name, category_id)
        select 'Sofas', v_furniture_id
        where not exists (select 1 from public.sub_categories where name = 'Sofas' and category_id = v_furniture_id);
    end if;

    -- Insert Electronics Subs
    if v_electronics_id is not null then
        insert into public.sub_categories (name, category_id)
        select 'Phones', v_electronics_id
        where not exists (select 1 from public.sub_categories where name = 'Phones' and category_id = v_electronics_id);

        insert into public.sub_categories (name, category_id)
        select 'Laptops', v_electronics_id
        where not exists (select 1 from public.sub_categories where name = 'Laptops' and category_id = v_electronics_id);
    end if;
    
    -- Insert Clothing Subs
    if v_clothing_id is not null then
        insert into public.sub_categories (name, category_id)
        select 'Men', v_clothing_id
        where not exists (select 1 from public.sub_categories where name = 'Men' and category_id = v_clothing_id);

        insert into public.sub_categories (name, category_id)
        select 'Women', v_clothing_id
        where not exists (select 1 from public.sub_categories where name = 'Women' and category_id = v_clothing_id);
    end if;
end $$;
